#    snapcraft yaml for tuxmathscrabble.
#    Copyright (C) 2021-2022 joker2770
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

# After registering a name on build.snapcraft.io, commit an uncommented line:
name: tuxmathscrabble
version: '0.8.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Tux Math Scrabble. # 79 char long summary
description: |
  Latest version 0.9.1 runs on Python3. Date: June 10, 2020
  Online/touch-screen version: http://ccosse.github.io/TuxMathScrabble-2015/
  Encourages kids to construct compound equations and consider multiple abstract possibilities.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18
architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf
  - build-on: arm64

plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

layout:
  /usr/share/midi/freepats:
    bind: $SNAP/usr/share/midi/freepats
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /etc/timidity:
    bind: $SNAP/etc/timidity
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  
apps:
  tuxmathscrabble:
    command-chain: ["snap/command-chain/alsa-launch"]
    command: usr/local/share/launcher.sh
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
    extensions: [gnome-3-28]
    plugs:
      - home
      - desktop
      - desktop-legacy
      - gsettings
      - wayland
      - unity7
      - x11
      - opengl
      - audio-playback
      - pulseaudio
      - alsa
      - removable-media
    
parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad

  env:
    after: [alsa-mixin]
    plugin: python
    python-version: python3
    python-packages:
      - pygame
    stage-packages:
      - freepats
      - libmodplug1
      - libopusfile0
      - libpulse0
      - libsndfile1
      - libmad0
      - libportmidi0
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-ttf-2.0-0
      - libxss1
      - libxxf86vm1
    build-packages:
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libfreetype6-dev
      - libportmidi-dev
      - libjpeg8-dev
      - python3-setuptools

  include-launcher:
    after: [env]
    plugin: dump
    source: "https://github.com/Joker2770/tuxmathscrabble-snap.git"
    source-depth: 1
    source-branch: main
    source-type: git
    organize:
      launcher.sh: usr/local/share/
    prime:
      - -TMS-Python3.tar*
      - -README*
      - -LICENSE
      - -snap
    override-build: |
      snapcraftctl build
      chmod +x launcher.sh

  include-code:
    after: [include-launcher]
    plugin: dump
    source: "https://git.code.sf.net/p/tuxmathscrabble/code"
    source-depth: 1
    source-branch: master
    source-type: git
    organize:
      '*': usr/local/share/
    prime:
      - -TuxMathScrabble-0.8.0.png
